In [1]:
import numpy as np

In [2]:
x = np.array([1.2, 0.9, 0.75, 0.8, 1.5])
x

array([1.2 , 0.9 , 0.75, 0.8 , 1.5 ])

##### Softmax

Returns the probability of each class, with the target class having the highest probability.

In [7]:
f_softmax = np.exp(x) / np.sum(np.exp(x))
f_softmax

array([0.22734376, 0.1684204 , 0.14496078, 0.15239308, 0.30688198])

##### ReLU

This function rectifies the values of the inputs that are less than zero by forcing them to zero(thus eliminating the vanishing gradient problem) and if the input is greater than 0, the output is equal to the input.

In [8]:
f_relu = np.maximum(0, x)
f_relu

array([1.2 , 0.9 , 0.75, 0.8 , 1.5 ])

##### Bipolar Sigmoid (𝜎 = 1)

The range of output for this function is from -1 to 1. It is closely related to the hyperbolic tangent function. It can be used as the activation function when the desired output range is between -1 and 1.

In [9]:
f_bip_sig = (1 - np.exp(-x)) / (1 + np.exp(-x))
f_bip_sig

array([0.53704957, 0.42189901, 0.3583574 , 0.37994896, 0.63514895])